"""add_refresh_token_rotation

Revision ID: 23fcb8973f0d
Revises: dd45db2ba7e5
Create Date: 2026-07-06 01:04:42.961781

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23fcb8973f0d'
down_revision = 'dd45db2ba7e5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Idempotent: the initial migration uses Base.metadata.create_all which may
    # already have created this table. Skip if it exists.
    from sqlalchemy import inspect
    conn = op.get_bind()
    if not inspect(conn).has_table('refresh_tokens'):
        op.create_table(
            'refresh_tokens',
            sa.Column('id', sa.String(), nullable=False),
            sa.Column('user_id', sa.String(), nullable=False),
            sa.Column('token_hash', sa.String(), nullable=False),
            sa.Column('jti', sa.String(), nullable=False),
            sa.Column('family_id', sa.String(), nullable=False),
            sa.Column('issued_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
            sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
            sa.Column('revoked', sa.Boolean(), nullable=False, server_default=sa.text('false')),
            sa.Column('replaced_by', sa.String(), nullable=True),
            sa.Column('user_agent', sa.String(), nullable=True),
            sa.Column('ip_address', sa.String(), nullable=True),
            sa.PrimaryKeyConstraint('id'),
            sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
            sa.UniqueConstraint('token_hash'),
            sa.UniqueConstraint('jti'),
        )
        op.create_index(op.f('ix_refresh_tokens_family_id'), 'refresh_tokens', ['family_id'], unique=False)
        op.create_index(op.f('ix_refresh_tokens_jti'), 'refresh_tokens', ['jti'], unique=True)
        op.create_index(op.f('ix_refresh_tokens_token_hash'), 'refresh_tokens', ['token_hash'], unique=True)
        op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    from sqlalchemy import inspect
    conn = op.get_bind()
    if inspect(conn).has_table('refresh_tokens'):
        op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
        op.drop_index(op.f('ix_refresh_tokens_token_hash'), table_name='refresh_tokens')
        op.drop_index(op.f('ix_refresh_tokens_jti'), table_name='refresh_tokens')
        op.drop_index(op.f('ix_refresh_tokens_family_id'), table_name='refresh_tokens')
        op.drop_table('refresh_tokens')
    # ### end Alembic commands ###
