"""add_password_reset_and_performance_indexes

Revision ID: dd45db2ba7e5
Revises: add_qtype_and_result_uq
Create Date: 2026-06-13 05:53:28.725019

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd45db2ba7e5'
down_revision = 'add_qtype_and_result_uq'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # Make the column additions idempotent: the initial migration (88db4dab6490)
    # uses Base.metadata.create_all() which may already include these columns on a
    # fresh database, so only add them if they are missing.
    from sqlalchemy import inspect
    conn = op.get_bind()
    inspector = inspect(conn)
    user_columns = {c['name'] for c in inspector.get_columns('users')}

    if 'reset_code' not in user_columns:
        op.add_column('users', sa.Column('reset_code', sa.String(), nullable=True))
    if 'reset_code_expires_at' not in user_columns:
        op.add_column('users', sa.Column('reset_code_expires_at', sa.DateTime(timezone=True), nullable=True))

    # Target Performance Indexes
    _create_index_if_not_exists('idx_assignments_course_id', 'assignments', ['course_id'])
    _create_index_if_not_exists('idx_quizzes_course_id', 'quizzes', ['course_id'])
    _create_index_if_not_exists('idx_modules_course_id', 'modules', ['course_id'])
    _create_index_if_not_exists('idx_lessons_module_id', 'lessons', ['module_id'])
    _create_index_if_not_exists('idx_enrollments_student_course', 'enrollments', ['student_profile_id', 'course_id'])
    _create_index_if_not_exists('idx_user_profiles_class_id', 'user_profiles', ['class_id'])
    _create_index_if_not_exists('idx_attendance_student_id', 'attendance', ['student_id'])

    # Date Sorted Indexes
    _create_index_if_not_exists('idx_assignments_created_at', 'assignments', ['created_at'])
    _create_index_if_not_exists('idx_quizzes_created_at', 'quizzes', ['created_at'])
    _create_index_if_not_exists('idx_exams_created_at', 'exams', ['created_at'])
    _create_index_if_not_exists('idx_results_graded_at', 'results', ['graded_at'])
    _create_index_if_not_exists('idx_attendance_created_at', 'attendance', ['created_at'])


def _create_index_if_not_exists(index_name, table_name, columns):
    from sqlalchemy import inspect
    conn = op.get_bind()
    inspector = inspect(conn)
    existing_indexes = {idx['name'] for idx in inspector.get_indexes(table_name)}
    if index_name not in existing_indexes:
        op.create_index(index_name, table_name, columns)


def downgrade() -> None:
    # Target Performance Indexes
    op.drop_index('idx_attendance_created_at', 'attendance')
    op.drop_index('idx_results_graded_at', 'results')
    op.drop_index('idx_exams_created_at', 'exams')
    op.drop_index('idx_quizzes_created_at', 'quizzes')
    op.drop_index('idx_assignments_created_at', 'assignments')
    op.drop_index('idx_attendance_student_id', 'attendance')
    op.drop_index('idx_user_profiles_class_id', 'user_profiles')
    op.drop_index('idx_enrollments_student_course', 'enrollments')
    op.drop_index('idx_lessons_module_id', 'lessons')
    op.drop_index('idx_modules_course_id', 'modules')
    op.drop_index('idx_quizzes_course_id', 'quizzes')
    op.drop_index('idx_assignments_course_id', 'assignments')

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'reset_code_expires_at')
    op.drop_column('users', 'reset_code')
    # ### end Alembic commands ###
